### ISSUE TITLE
cs_siege needing fixed?

### ISSUE THREAD

**Issue by APGRoboCop** [yapb/graph#45]
Hello, I've noticed this latest YaPB build and graph for cs_siege shows that the bots appear to struggle when they go underground into the elevator and fail to press the elevator button. They instead just appear stuck and won't climb up nor will press the button from there:
![download](https://user-images.githubusercontent.com/3459575/167305417-e1deda24-9699-4757-ae2d-81c6fe3bba41.jpg)

**Comment by Drevny13** [comment]
I tried to fix it as much as possible
-with command yb wp clean all - clean all unnecessary connections
-now all the ways when climbing from below go through the elevator call button, the bot must first press and then enter the elevator. Ideally,  need to add a stop function to the bot on the waypoint for a certain number of seconds so that it does not run out of the elevator until the elevator starts to rise
-from above, on the contrary, I made a descent down only through the stairs (a flag without hostages is automatically placed on the stairway's waypoint)
[cs_siege.zip](https://github.com/yapb/graph/files/8687203/cs_siege.zip)

**Comment by APGRoboCop** [comment]
Yes well, I guess that's the problem with poorly designed maps and elevators and maybe ladders. It's no wonder they tend to get squashed to death in as_oilrig with the elevator platform descending and killing them. Thanks anyway...
