### ISSUE TITLE
make the study of the map by bots like zbot

### ISSUE THREAD

**Issue by TheArtemMaps** [yapb/graph#58]
hi, @jeefo can you make studying of map like zbot doing. like when i adding bots, they automaticly creating waypoints for each map, that i entering. is thath pissoble tho?

**Comment by jeefo** [comment]
I believe it's not currently possible.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: TheArtemMaps ***@***.***>
Sent: Tuesday, September 20, 2022 8:15:25 PM
To: yapb/graph ***@***.***>
Cc: jeefo ***@***.***>; Mention ***@***.***>
Subject: [yapb/graph] make the study of the map by bots like zbot (Issue #58)


hi, @jeefo<https://github.com/jeefo> can you make studying of map like zbot doing. like when i adding bots, they automaticly creating waypoints for each map, that i entering. is thath pissoble tho?

**Comment by Drevny13** [comment]
old cs bot real bot 
https://github.com/Fundynamic/RealBot
I like him in some moments.
there are a lot of bugs and development is abandoned, he uses the same points for moving bots as yapb, but he puts them automatically. That is, you can play a little on the map or just run alone. The bot will automatically put dots behind you, something like the autowaypoint option in yapb
interestingly , if you first make paths for yapb , launch a server with bots without players and add one realbot bot . Real will completely repeat and copy the yapb move
I would like to see the same option in yapb, so that yapb automatically sets points during the game and removes automatically blocked paths , falls from heights, bug corners, etc.
As an example, the bot automatically built a path through a transparent grid as on an assault, but since it cannot pass through it, after trying to jump over or go around a little from the side, if this is not possible  bot automatically removes it. I think all these features can be implemented. Need to increase the density of automatic points, make them without a radius
This method i think has advantages compared to navzones, more accurate movement of the bot, accurate jumps, the main thing is to leave successful jumps and remove the unsuccessful ones automatically
or maybe possible combine nav zones on simple spaces map and use successful jumps of players when jumping

**Comment by jeefo** [comment]
The CS-EBOT project that i have mentioned in "If u need new feature", 
has this feature. I believe i could backport it back to YaPB  someday, 
if anyone test this function works somewhat correctly there.

**Comment by jeefo** [comment]
https://github.com/yapb/yapb/pull/439

however such will not uploadable to DB, without hand-fixing
