### ISSUE TITLE
Add bots in this map please THANKS

### ISSUE THREAD

**Issue by bobito1993** [yapb/graph#7]
zm_fun_world_b
xld-zm_dust
zm_defense_xld
zm_battleground_foda
zm_restart_v3
zm_snow_world
zm_ice_attack_hd
zm_vip_gray

**Comment by PRinceBhai** [comment]
@Vladislav4KZ How do you play these maps? Can you explain? I've never played Zombie Mode before so I don't know where to put the Goal and Team specific Important Waypoints.

**Comment by Vladislav4KZ** [comment]
@PRinceBhai I haven't played Zombie Mode maps with bots.

But my guess is to put the Counter-Terrorists important nodes in a human hideout. As a rule, these are some buildings to which stairs lead.

Because Counter-Terrorists team is a humans, and the Terrorists team is a zombies.

About the Terrorists important nodes and the Map Goal node on such maps, I don't know how to use them strategically.

All of the above applies to Zombie Plague maps.



For Zombie Escape maps, I think the Map Goal node can be used to indicate where people need to go to escape the zombies.

I have not tested how bots will behave in practice when creating such waypoints.

**Comment by PRinceBhai** [comment]
@bobito1993 @Vladislav4KZ Done.
